apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: metadata-postgres-secret
  namespace: backend-veyor
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "test-password"
  POSTGRES_DB: "veyor_metadata"
