apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: backend-veyor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      # serviceAccountName
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
        fsGroupChangePolicy: "Always"
        # supplementalGroups:
          # - 0
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
      containers:
        - name: grafana
          image: grafana/grafana:10.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
