apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: backend-veyor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # serviceAccountName
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      volumes:
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: prometheus-config
        configMap:
          name: prometheus-config
      containers: 
      - name: prometheus
        image: prom/prometheus:main-distroless
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: prometheus-storage
          mountPath: /prometheus
        - name: prometheus-config
          mountPath: /etc/prometheus
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.retention.size=4GB"
          - "--web.enable-lifecycle"